config/routes.rb
Cuapp::Application.routes.draw do
  
  resources :things

  get "app/index"

  get "app/contact"

  get "app/channel"

  get "app/chat"

  get "user/index"

  match "user/signup"

  post "user/signin"

  get "user/signout"

  get "user/account"

  get "page/home"
  
  root :to => 'page#home'

end

app/models/chat.rb
class Chat < ActiveRecord::Base
  attr_accessible :chat_channel_id, :content, :read, :user_id
  belongs_to :chat_channel
  belongs_to :user
  validates_associated :user, :chat_channel
end

app/models/chat_channel.rb
class ChatChannel < ActiveRecord::Base
  attr_accessible :active, :initiator_id, :type
  belongs_to :initiator, :class_name => 'User', :foreign_key => 'initiator_id'
  has_many :chat_channel_subscribers
  has_many :users, :through => :chat_channel_subscribers
  validates_associated :initiator
end

app/models/chat_channel_subscriber.rb
class ChatChannelSubscriber < ActiveRecord::Base
  attr_accessible :chat_channel_id, :user_id
  belongs_to :user
  belongs_to :chat_channel
  validates_associated :user, :chat_channel
end

app/models/friend_connection.rb
class FriendConnection < ActiveRecord::Base
  attr_accessible :confirm, :friend_id, :user_id
  belongs_to :user
  belongs_to :friend, :class_name => 'User', :foreign_key => :friend_id
  after_create :adding_target_as_friend_to_who_requested
  after_destroy :remove_target_friend_where_friend_is_user
  validates_associated :user, :friend
  def adding_target_as_friend_to_who_requested
    FriendConnection.skip_callback(:create, :after, :adding_target_as_friend_to_who_requested)
    rel = FriendConnection.new
    rel.user = friend
    rel.friend = user
    rel.save
    FriendConnection.set_callback(:create, :after, :adding_target_as_friend_to_who_requested)
    return
  end
  def remove_target_friend_where_friend_is_user
    target = friend.friend_connections.find_by_friend_id(user.id)
    target.destroy if target != nil
  end
end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :archive, :confirm_action, :description, :refuse_action, :user_id
  
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  attr_accessible :content
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :activation_key, :active, :bio, :complete_name, :email, :password, :username, :token_key
  has_many :chats
  has_many :chat_channel_subscribers
  has_many :chat_channels, :through => :chat_channel_subscribers
  has_many :friend_connections
  has_many :friends, :through => :friend_connections
  
  before_create :before_create_cb
  validates_uniqueness_of :username, :email
  validates_presence_of :username, :email, :password, :complete_name
 
  def self.signup param
    new_user = User.new(param)
    raise Exception.new(new_user.errors.to_a.join(',')) if !new_user.valid? 
    new_user.save
    new_user
  end
  def self.signin email, password
    User.where('email = ? and password = ?', email, Digest::SHA1.hexdigest(password)).last
  end
  def password=(string)
     write_attribute(:password , Digest::SHA1.hexdigest(string))
  end
  def before_create_cb
    write_attribute(:activation_key , Digest::SHA1.hexdigest(Time.now.to_s))
    write_attribute(:active , false)
    write_attribute(:token_key, Digest::SHA1.hexdigest((Time.now+4.day).to_s))
    return
  end
  def self.aut email, password
    u = User.find_by_email_and_password(email, Digest::SHA1.hexdigest(password)) 
    raise Exception.new("Wrong Combination") if u == nil
    raise Exception.new("no active yet") if u.active != true
    u
  end
    
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  def index
  end

  def contact
  end

  def channel
  end

  def chat
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  # GET /things
  # GET /things.json
  def index
    @things = Thing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @things }
    end
  end

  # GET /things/1
  # GET /things/1.json
  def show
    @thing = Thing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @thing }
    end
  end

  # GET /things/new
  # GET /things/new.json
  def new
    @thing = Thing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @thing }
    end
  end

  # GET /things/1/edit
  def edit
    @thing = Thing.find(params[:id])
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(params[:thing])

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render json: @thing, status: :created, location: @thing }
      else
        format.html { render action: "new" }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /things/1
  # PUT /things/1.json
  def update
    @thing = Thing.find(params[:id])

    respond_to do |format|
      if @thing.update_attributes(params[:thing])
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing = Thing.find(params[:id])
    @thing.destroy

    respond_to do |format|
      format.html { redirect_to things_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  
  end

  def signup
    begin
      user = User.signup(params[:register])
      render :json => {:success => 'Signup Success, please check your email for further info'}
    rescue Exception => e
      render :json => {:error => e.message}, :status => 400
    end
    
  end

  def signin
    begin
       u = User.signin(params[:email], params[:password])
      session[:user_current] = u.id  if u != nil
     
      redirect_to '/app'
    rescue Exception => e
      raise e
    end
    
  end

  def signout
  end

  def account
  end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/app/channel.html.haml
%h1 App#channel
%p Find me in app/views/app/channel.html.haml

app/views/app/chat.html.haml
%h1 App#chat
%p Find me in app/views/app/chat.html.haml

app/views/app/contact.html.haml
%h1 App#contact
%p Find me in app/views/app/contact.html.haml

app/views/app/index.html.haml
%h1 App#index
%p Find me in app/views/app/index.html.haml

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title CuApp
		%meta{:charset => "utf-8"}
		%meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
		%meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
		= stylesheet_link_tag :application, :media => "all"
		= javascript_include_tag :application
		= csrf_meta_tags
		= yield :head_js
	%body
		#container.container
			#main{:class => "main"}
				= yield
		%footer
		= yield :bottom_js

app/views/page/home.html.haml
%h1.center-text CuApp
%hr
#sign-form.relative
	.row-fluid
		.span12
			%form
				.form-horizontal
					.control-group
						%label.control-label Email
						.controls
							%input{:type => 'text', :name => 'email'}
					.control-group
						%label.control-label Password
						.controls
							%input{:type => 'password', :name => 'password'}
				%hr
				.actions.center-text
					%button.btn.btn-info
						%i.icon.icon-signin
						Signin
					%span.btn#show-signupform 
						%i.icon.icon-edit
						Signup
					
#signup-form.relative.hide
	.row-fluid
		.span12
			%form
				.form-horizontal
					.control-group
						%label.control-label Complete Name
						.controls
							%input{:type => 'text', :name => 'register[complete_name]'}
					.control-group
						%label.control-label Username
						.controls
							%input{:type => 'text', :name => 'register[username]'}
					%hr
					.control-group
						%label.control-label Email
						.controls
							%input{:type => 'text', :name => 'register[email]'}
					.control-group
						%label.control-label Password
						.controls
							%input{:type => 'password', :name => 'register[password]'}
					.actions.center-text
						%button.btn.btn-info
							%i.icon.icon-edit
							Signup
						%span.btn#show_signin_form
							%i.icon.icon-signin
							Signin
=content_for :bottom_js do
	:javascript
			$(document).ready(function(){
				$('#show-signupform').live('click', function(){
					showSignupForm()
				})
				$('#show_signin_form').live('click', function(){
					showSigninForm()
				})
				$('#signup-form form').submit(function(e){
					e.preventDefault()
					signup();
				})
				$('#sign-form form').submit(function(e){
					e.preventDefault()
					signin()
				})
				
			})
			function signup(){
					var data = $('#signup-form form').serialize();
					$.ajax({
						url : "#{user_signup_path}",
						data : data,
						type : 'post',
						dataType : 'json',
						success: function(res){
							
						},
						error: function(res){
							
						}
						
					})
			}
			function signin(){
				var data = $('#sign-form form').serialize();
				$.ajax({
					url : "#{user_signin_path}",
					data : data,
					type : 'post',
					dataType : 'json',
					success: function(res){
						
					},
					error: function(res){
						
					}
					
				})
			}
			function showSigninForm(){
				$('#signup-form').transit({
					right: '-500px'
				}, 500 , 'ease', function(){
					$('#signup-form').addClass('hide')
					$('#sign-form').removeClass('hide').transit({
						left:'0px'
					})
					
				})
			}
			function showSignupForm(){
				$('#sign-form').transit({
					left: '-500px' 
				}, 500, 'ease', function(){
					$('#sign-form').addClass('hide')
					$('#signup-form').css({right:'-500px'}).removeClass('hide').transit({
						right: '0px',
						
					})
				})
			}
			
		
			
		
							
					
		
		
		

app/views/things/_form.html.haml
= form_for @thing do |f|
  -if @thing.errors.any?
    #error_explanation
      %h2= "#{pluralize(@thing.errors.count, "error")} prohibited this thing from being saved:"
      %ul
        - @thing.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/things/edit.html.haml
%h1 Editing thing

= render 'form'

= link_to 'Show', @thing
\|
= link_to 'Back', things_path

app/views/things/index.html.haml
%h1 Listing things

%table
  %tr
    %th Content
    %th
    %th
    %th

  - @things.each do |thing|
    %tr
      %td= thing.content
      %td= link_to 'Show', thing
      %td= link_to 'Edit', edit_thing_path(thing)
      %td= link_to 'Destroy', thing, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Thing', new_thing_path

app/views/things/new.html.haml
%h1 New thing

= render 'form'

= link_to 'Back', things_path

app/views/things/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @thing.content

= link_to 'Edit', edit_thing_path(@thing)
\|
= link_to 'Back', things_path

app/views/user/account.html.haml
%h1 User#account
%p Find me in app/views/user/account.html.haml

app/views/user/index.html.haml
%h1 User#index
%p Find me in app/views/user/index.html.haml

app/views/user/register.html.haml
%h1 User#register
%p Find me in app/views/user/register.html.haml

app/views/user/signin.html.haml
%h1 User#signin
%p Find me in app/views/user/signin.html.haml

app/views/user/signout.html.haml
%h1 User#signout
%p Find me in app/views/user/signout.html.haml